######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 26 18:14:17 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ..
INCLUDEPATH += ../include
QT += network
LIBS +=  -lqjson

# Input
HEADERS += \
stubclientgui.h \
testcontroller.h \
testconfig.h

SOURCES += \
testcontroller.cpp \
testconfig.cpp \
../controller.cpp \
../modelcontact.cpp \
../imodel.cpp \
../network.cpp \
../modellog.cpp
