# - Find libyajl library and headers - http://lloyd.github.com/yajl
# The module defines the following variables:
#
#  YAJL_FOUND
#  YAJL_INCLUDE_DIRS
#  YAJL_LIBRARIES
#  YAJL_VERSION
#
# If YAJL_VERSION equal to "system", it means it was not find with pkg-config.

# Copyright (c) 2013 Tristan Le Guern <leguern AT medu.se>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Check if the definitions are not already in cache
IF(YAJL_INCLUDE_DIRS AND YAJL_LIBRARIES)
    SET(YAJL_FIND_QUIETLY TRUE)
ENDIF(YAJL_INCLUDE_DIRS AND YAJL_LIBRARIES)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_YAJL yajl)
SET(YAJL_VERSION ${PC_YAJL_VERSION})
SET(YAJL_DEFINITIONS ${PC_YAJL_DEFINITIONS})

FIND_PATH(YAJL_INCLUDE_DIR yajl_parse.h
    HINTS ${PC_YAJL_INCLUDE_DIRS}
)

FIND_LIBRARY(YAJL_LIBRARY NAMES yajl libyajl 
    HINTS ${PC_YAJL_LIBRARY_DIRS}
)

IF(YAJL_INCLUDE_DIR STREQUAL YAJL_LIBRARY-NOTFOUND
  OR YAJL_LIBRARY STREQUAL YAJL_LIBRARY-NOTFOUND)
    UNSET(YAJL_FOUND)
ELSE()
    IF(NOT YAJL_VERSION)
        MESSAGE(STATUS "  but non-package 'yajl' found")
        SET(YAJL_VERSION "system")
    ENDIF(NOT YAJL_VERSION)
    SET(YAJL_FOUND TRUE)

    # cmake GUI niceness
    MARK_AS_ADVANCED(YAJL_INCLUDE_DIR YAJL_LIBRARY)
ENDIF()

IF(YAJL_FOUND)
    SET(YAJL_LIBRARIES ${YAJL_LIBRARY})
    SET(YAJL_INCLUDE_DIRS ${YAJL_INCLUDE_DIR})
ENDIF(YAJL_FOUND)

