# - Find libtclt library and headers
# The module defines the following variables:
#
#  TCLT_FOUND
#  TCLT_INCLUDE_DIRS
#  TCLT_LIBRARIES
#  TCLT_VERSION
#
# If TCLT_VERSION equal to "system", it means it was not find with pkg-config.

# Copyright (c) 2013 Tristan Le Guern <leguern AT medu.se>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Check if the definitions are not already in cache
IF(TCLT_INCLUDE_DIRS AND TCLT_LIBRARIES)
    SET(TCLT_FIND_QUIETLY TRUE)
ENDIF(TCLT_INCLUDE_DIRS AND TCLT_LIBRARIES)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_TCLT libtclt)
SET(TCLT_VERSION ${PC_TCLT_VERSION})
SET(TCLT_DEFINITIONS ${PC_TCLT_DEFINITIONS})

FIND_PATH(TCLT_INCLUDE_DIR tclt.h
    HINTS ${PC_TCLT_INCLUDE_DIRS}
)

FIND_LIBRARY(TCLT_LIBRARY NAMES tclt libtclt 
    HINTS ${PC_TCLT_LIBRARY_DIRS}
)

IF(TCLT_INCLUDE_DIR STREQUAL TCLT_LIBRARY-NOTFOUND
  OR TCLT_LIBRARY STREQUAL TCLT_LIBRARY-NOTFOUND)
    UNSET(TCLT_FOUND)
ELSE()
    IF(NOT TCLT_VERSION)
        MESSAGE(STATUS "  but non-package 'libtclt' found")
        SET(TCLT_VERSION "system")
    ENDIF(NOT TCLT_VERSION)
    SET(TCLT_FOUND TRUE)

    # cmake GUI niceness
    MARK_AS_ADVANCED(TCLT_INCLUDE_DIR TCLT_LIBRARY)
ENDIF()

IF(TCLT_FOUND)
    SET(TCLT_LIBRARIES ${TCLT_LIBRARY})
    SET(TCLT_INCLUDE_DIRS ${TCLT_INCLUDE_DIR})
ENDIF(TCLT_FOUND)

