# - Find libtuntap library and headers
# The module defines the following variables:
#
#  TUNTAP_FOUND
#  TUNTAP_INCLUDE_DIRS
#  TUNTAP_LIBRARIES
#  TUNTAP_VERSION
#
# If TUNTAP_VERSION equal to "system", it means it was not find with pkg-config.

# Copyright (c) 2013 Tristan Le Guern <leguern AT medu.se>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Check if the definitions are not already in cache
IF(TUNTAP_INCLUDE_DIRS AND TUNTAP_LIBRARIES)
    SET(TUNTAP_FIND_QUIETLY TRUE)
ENDIF(TUNTAP_INCLUDE_DIRS AND TUNTAP_LIBRARIES)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_TUNTAP libtuntap)
SET(TUNTAP_VERSION ${PC_TUNTAP_VERSION})
SET(TUNTAP_DEFINITIONS ${PC_TUNTAP_DEFINITIONS})

FIND_PATH(TUNTAP_INCLUDE_DIR tuntap.h
    HINTS ${PC_TUNTAP_INCLUDE_DIRS}
)

FIND_LIBRARY(TUNTAP_LIBRARY NAMES tuntap libtuntap
    HINTS ${PC_TUNTAP_LIBRARY_DIRS}
)

IF(TUNTAP_INCLUDE_DIR STREQUAL TUNTAP_INCLUDE_DIR-NOTFOUND
  OR TUNTAP_LIBRARY STREQUAL TUNTAP_LIBRARY-NOTFOUND)
    UNSET(TUNTAP_FOUND)
ELSE()
    IF(NOT TUNTAP_VERSION)
        MESSAGE(STATUS "  but non-package 'libtuntap' found")
        SET(TUNTAP_VERSION "system")
    ENDIF(NOT TUNTAP_VERSION)
    SET(TUNTAP_FOUND TRUE)

    # cmake GUI niceness
    MARK_AS_ADVANCED(TUNTAP_INCLUDE_DIR TUNTAP_LIBRARY)
ENDIF()

IF(TUNTAP_FOUND)
    SET(TUNTAP_LIBRARIES ${TUNTAP_LIBRARY})
    SET(TUNTAP_INCLUDE_DIRS ${TUNTAP_INCLUDE_DIR})
ENDIF(TUNTAP_FOUND)

