# - Find libtapcfg library and headers
# The module defines the following variables:
#
#  TAPCFG_FOUND
#  TAPCFG_INCLUDE_DIRS
#  TAPCFG_LIBRARIES
#  TAPCFG_VERSION
#
# If TAPCFG_VERSION equal to "system", it means it was not find with pkg-config.

# Copyright (c) 2013 Tristan Le Guern <leguern AT medu.se>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Check if the definitions are not already in cache
IF(TAPCFG_INCLUDE_DIRS AND TAPCFG_LIBRARIES)
    SET(TAPCFG_FIND_QUIETLY TRUE)
ENDIF(TAPCFG_INCLUDE_DIRS AND TAPCFG_LIBRARIES)

FIND_PACKAGE(PkgConfig QUIET)
PKG_CHECK_MODULES(PC_TAPCFG libtapcfg)
SET(TAPCFG_VERSION ${PC_TAPCFG_VERSION})
SET(TAPCFG_DEFINITIONS ${PC_TAPCFG_DEFINITIONS})

FIND_PATH(TAPCFG_INCLUDE_DIR tapcfg.h
    HINTS ${PC_TAPCFG_INCLUDE_DIRS}
)

FIND_LIBRARY(TAPCFG_LIBRARY NAMES tapcfg libtapcfg
    HINTS ${PC_TAPCFG_LIBRARY_DIRS}
)

IF(TAPCFG_INCLUDE_DIR STREQUAL TAPCFG_LIBRARY-NOTFOUND
  OR TAPCFG_LIBRARY STREQUAL TAPCFG_LIBRARY-NOTFOUND)
    UNSET(TAPCFG_FOUND)
ELSE()
    IF(NOT TAPCFG_VERSION)
        MESSAGE(STATUS "  but non-package 'libtapcfg' found")
        SET(TAPCFG_VERSION "system")
    ENDIF(NOT TAPCFG_VERSION)
    SET(TAPCFG_FOUND TRUE)

    # cmake GUI niceness
    MARK_AS_ADVANCED(TAPCFG_INCLUDE_DIR TAPCFG_LIBRARY)
ENDIF()

IF(TAPCFG_FOUND)
    SET(TAPCFG_LIBRARIES ${TAPCFG_LIBRARY})
    SET(TAPCFG_INCLUDE_DIRS ${TAPCFG_INCLUDE_DIR})
ENDIF(TAPCFG_FOUND)

